# NOTE: it is best to use absolute paths
# If you must use relative paths, they are relative
# to run.py, not the config file

seed: 81

dataset:
  name: 'SeriesDataset'
  sampler:
    name: 'BalancedELVOSampler'
    weights: [0.5, 0.25, 0.25]
  params:
    hu_augment: 5
    num_slices: 64
    flip: True
    reverse: True
  inner_fold: 0
  outer_fold: 1
  data_dir: '../data/rih/mips/'
  csv_filename: '../data/rih/train_quick_mips_with_splits_cv10x10.csv'


transform:
  augment: 'spatial_and_noise'
  probability: 1.0
  num_workers: 0
  pad_ratio: 1.0
  resize_to: [256, 256]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model:
  name: 'Net3D'
  params:
    num_classes: 3
    backbone: 'fastonly_r50'
    dropout: 0.2
    pretrained: True
    wso_params:
      wl: [50,  200,  50]
      ww: [400, 1000, 400]
      dim: 3


find_lr: # this is its own mode 
  params:
    start_lr: 1.0e-7
    end_lr: 1
    num_iter: 500
    save_fig: True


train:
  outer_only: False
  batch_size: 16
  trainer: 'Trainer'
  params:
    gradient_accumulation: 1
    num_epochs: 50
    steps_per_epoch: 0
    validate_interval: 2
    verbosity: 100
    amp: True


evaluation:
  batch_size: 2
  evaluator: 'Evaluator'
  params:
    save_checkpoint_dir: '../checkpoints/cv-fast50/i0o1/'
    save_best: True
    prefix: 'fast50'
    metrics: ['average_auc', 'auc_elvo', 'auc_acute', 'avp_elvo', 'avp_acute', 'average_f1', 'accuracy']
    valid_metric: ['auc_acute', 'auc_elvo']
    mode: 'max'
    improve_thresh: 1.0e-6
    early_stopping: 5


loss:
  name: 'CrossEntropyLoss'
  params:


optimizer:
  name: 'AdamW'
  params:
    lr: 1.2e-5
    weight_decay: 5.0e-4


scheduler:
  name: 'CustomOneCycleLR'
  params:
    max_lr:   3.0e-4
    final_lr: 1.0e-12
    pct_start: 0.3
    anneal_strategy: 'linear'
    cycle_momentum: False


test:
  checkpoint: '../checkpoints/cv-i3d/i0o1/I3D_011_VM-0.8076.PTH'
  batch_size: 16
  save_preds_dir: '../cv-predictions/cv-i3d/i0o1/'
  predictor: 'Predictor'
  params:
    labels_available: True


predict:
  checkpoint: '.pth'
  batch_size: 128
  data_dir:
  save_preds_dir:
  outer_only: True
   