seed: 88


dataset:
  name: 'DICOMDataset'
  params:
    num_slices: 64
  data_dir: '../data/'
  csv_filename: '../data/penn/series_metadata.csv'


transform:
  augment: null
  num_workers: 0
  pad_ratio: 1.0
  resize_to: [256, 256]
  preprocess:
    image_range: [0, 255]
    input_range: [0, 1]
    mean: [0.485, 0.456, 0.406]
    sdev: [0.229, 0.224, 0.225]


model_configs:
  - 'configs/experiments/experiment025.yaml'


model_weights: [1.]


checkpoints:
  - '../checkpoints/experiment025/R50_013_VM-0.9697.PTH'


predict:
  batch_size: 1
  save_preds_dir: '../data/penn/'
  predictor: 'Predictor'
  params:
    labels_available: False
